;;;; packages/core/text/src/domain/codec-zip.lisp
;;;;
;;;; zip archives (PKWARE APPNOTE): the central directory is authoritative
;;;; for reading; stored and deflated entries are supported. ZIP64,
;;;; encryption, multi-disk archives, and other methods raise
;;;; ARCHIVE-UNSUPPORTED rather than being misread. Entry times are MS-DOS
;;;; local times without a zone; they are read and written as UTC so the same
;;;; archive lists the same way on every host.
(in-package #:aitools.text.domain)

(defun days-from-civil (year month day)
  "Days since 1970-01-01 for a proleptic Gregorian date (H. Hinnant)."
  (let* ((y (if (<= month 2) (1- year) year))
         (era (floor y 400))
         (yoe (- y (* era 400)))
         (doy (+ (floor (+ (* 153 (+ month (if (> month 2) -3 9))) 2) 5) (1- day)))
         (doe (+ (* yoe 365) (floor yoe 4) (- (floor yoe 100)) doy)))
    (+ (* era 146097) doe -719468)))

(defun %dos-time-to-unix (time date)
  (let ((year (+ 1980 (ldb (byte 7 9) date)))
        (month (max 1 (min 12 (ldb (byte 4 5) date))))
        (day (max 1 (min 31 (ldb (byte 5 0) date)))))
    (+ (* 86400 (days-from-civil year month day))
       (* 3600 (min 23 (ldb (byte 5 11) time)))
       (* 60 (min 59 (ldb (byte 6 5) time)))
       (* 2 (min 29 (ldb (byte 5 0) time))))))

(defun %unix-to-dos-time (unix)
  "(VALUES TIME DATE), clamped to MS-DOS's 1980-2107 range."
  (multiple-value-bind (second minute hour day month year)
      (decode-universal-time
       (aitools.kernel.domain:unix-seconds-to-universal-time (max unix 315532800)) 0)
    (if (> year 2107)
        (values #xBF7D #xFF9F)
        (values (logior (ash hour 11) (ash minute 5) (floor second 2))
                (logior (ash (- year 1980) 9) (ash month 5) day)))))

(defun %zip-signature-p (octets offset signature)
  (and (<= 0 offset) (<= (+ offset 4) (length octets))
       (= (%u32le octets offset) signature)))

(defun %find-end-of-central-directory (octets)
  (let ((length (length octets)))
    (when (< length 22) (%archive-fail "too short to be a zip archive"))
    (loop for offset from (- length 22) downto (max 0 (- length 22 65535))
          when (and (%zip-signature-p octets offset #x06054b50)
                    (<= (+ offset 22 (%u16le octets (+ offset 20))) length))
            return offset
          finally (%archive-fail "no zip end-of-central-directory record"))))

(defun %zip-kind-and-mode (made-by external name)
  (let ((unix-mode (and (= (ash made-by -8) 3) (ash external -16))))
    (if (and unix-mode (plusp unix-mode))
        (values (case (logand unix-mode #o170000)
                  (#o040000 :directory)
                  (#o120000 :symlink)
                  (#o100000 :file)
                  (t (if (and (plusp (length name)) (char= (char name (1- (length name))) #\/))
                         :directory :other)))
                (logand unix-mode #o7777))
        (values (if (or (logbitp 4 external)
                        (and (plusp (length name)) (char= (char name (1- (length name))) #\/)))
                    :directory :file)
                nil))))

(defun read-zip-entries (octets)
  "The ARCHIVE-ENTRY list of the zip archive OCTETS in central directory
order. Directory names lose their trailing `/`. A symlink's target is read
from its (small) data."
  (declare (type octets octets))
  (let* ((eocd (%find-end-of-central-directory octets))
         (disk (%u16le octets (+ eocd 4)))
         (count (%u16le octets (+ eocd 10)))
         (directory-size (%u32le octets (+ eocd 12)))
         (directory-offset (%u32le octets (+ eocd 16))))
    (when (or (%zip-signature-p octets (- eocd 20) #x07064b50)
              (= count #xFFFF) (= directory-size #xFFFFFFFF) (= directory-offset #xFFFFFFFF))
      (%archive-unsupported "ZIP64"))
    (unless (zerop disk) (%archive-unsupported "multi-disk zip"))
    (when (> (+ directory-offset directory-size) eocd)
      (%archive-fail "central directory lies outside the archive"))
    (let ((offset directory-offset) (entries '()))
      (dotimes (i count (nreverse entries))
        (unless (%zip-signature-p octets offset #x02014b50)
          (%archive-fail "bad central directory entry signature"))
        (let* ((made-by (%u16le octets (+ offset 4)))
               (flags (%u16le octets (+ offset 8)))
               (method (%u16le octets (+ offset 10)))
               (time (%u16le octets (+ offset 12)))
               (date (%u16le octets (+ offset 14)))
               (crc (%u32le octets (+ offset 16)))
               (compressed (%u32le octets (+ offset 20)))
               (size (%u32le octets (+ offset 24)))
               (name-length (%u16le octets (+ offset 28)))
               (extra-length (%u16le octets (+ offset 30)))
               (comment-length (%u16le octets (+ offset 32)))
               (external (%u32le octets (+ offset 38)))
               (local (%u32le octets (+ offset 42)))
               (name-start (+ offset 46))
               (next (+ name-start name-length extra-length comment-length)))
          (when (> next (length octets)) (%archive-fail "central directory entry is truncated"))
          (when (or (= compressed #xFFFFFFFF) (= size #xFFFFFFFF) (= local #xFFFFFFFF))
            (%archive-unsupported "ZIP64"))
          (unless (%zip-signature-p octets local #x04034b50)
            (%archive-fail "bad local header signature"))
          (let* ((data-offset (+ local 30 (%u16le octets (+ local 26)) (%u16le octets (+ local 28))))
                 (raw-name (if (logbitp 11 flags)
                               (decode-utf8 octets :start name-start :end (+ name-start name-length))
                               (%name-from-octets octets name-start (+ name-start name-length)))))
            (when (> (+ data-offset compressed) (length octets))
              (%archive-fail "entry data lies outside the archive"))
            (multiple-value-bind (kind mode) (%zip-kind-and-mode made-by external raw-name)
              (let ((entry (make-archive-entry :format :zip
                                               :name (string-right-trim "/" raw-name)
                                               :kind kind :size size :mode mode
                                               :mtime (%dos-time-to-unix time date)
                                               :data-offset data-offset :compressed-size compressed
                                               :method method :flags flags :crc crc)))
                (push (if (eq kind :symlink)
                          (make-archive-entry :format :zip :name (archive-entry-name entry)
                                              :kind kind :size size :mode mode
                                              :mtime (archive-entry-mtime entry)
                                              :link-target (decode-utf8
                                                            (archive-entry-data octets entry :max-output 4096))
                                              :data-offset data-offset :compressed-size compressed
                                              :method method :flags flags :crc crc)
                          entry)
                      entries))))
          (setf offset next))))))

(defun %zip-entry-data (octets entry max-output)
  (let ((size (archive-entry-size entry))
        (start (archive-entry-data-offset entry))
        (compressed (archive-entry-compressed-size entry)))
    (when (logbitp 0 (archive-entry-flags entry)) (%archive-unsupported "encrypted zip entry"))
    (when (and max-output (> size max-output))
      (error 'archive-limit-exceeded :limit max-output :reason "entry size"))
    (let ((data (case (archive-entry-method entry)
                  (0 (unless (= size compressed) (%archive-fail "stored entry sizes disagree"))
                   (subseq octets start (+ start size)))
                  (8 (handler-case (inflate octets :start start :end (+ start compressed) :max-output size)
                       (archive-limit-exceeded ()
                         (%archive-fail "entry inflates past its declared size"))))
                  (t (%archive-unsupported "zip compression method")))))
      (unless (= (length data) size) (%archive-fail "entry size mismatch"))
      (unless (= (crc32 data) (archive-entry-crc entry)) (%archive-fail "zip CRC-32 mismatch"))
      data)))

;;; ------------------------------------------------------------ writing

(defun %byte-sink ()
  (make-array 1024 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))

(defun %put-u16le (sink value)
  (vector-push-extend (ldb (byte 8 0) value) sink)
  (vector-push-extend (ldb (byte 8 8) value) sink))

(defun %put-u32le (sink value)
  (%put-u16le sink (ldb (byte 16 0) value))
  (%put-u16le sink (ldb (byte 16 16) value)))

(defun %put-octets (sink octets)
  (loop for byte across octets do (vector-push-extend byte sink)))

(defun %member-payload (member)
  (ecase (archive-member-kind member)
    (:file (archive-member-data member))
    (:symlink (encode-utf8 (or (archive-member-link-target member) "")))
    (:directory (make-array 0 :element-type '(unsigned-byte 8)))))

(defun %member-unix-mode (member)
  (logior (archive-member-mode member)
          (ecase (archive-member-kind member)
            (:file #o100000) (:directory #o040000) (:symlink #o120000))))

(defun write-zip (members)
  "A zip archive holding MEMBERS (ARCHIVE-MEMBERs) in order. File data is
deflated when that is smaller, else stored. Names are UTF-8 (flag bit 11 set
when non-ASCII). Signals ARCHIVE-UNSUPPORTED past the non-ZIP64 limits."
  (when (> (length members) #xFFFF) (%archive-unsupported "more than 65535 zip entries"))
  (let ((sink (%byte-sink)) (central '()))
    (dolist (member members)
      (let* ((name (encode-utf8 (if (eq (archive-member-kind member) :directory)
                                    (concatenate 'string (archive-member-name member) "/")
                                    (archive-member-name member))))
             (flags (if (find-if (lambda (byte) (>= byte #x80)) name) #x0800 0))
             (data (%member-payload member))
             (deflated (and (eq (archive-member-kind member) :file) (plusp (length data)) (deflate data)))
             (method (if (and deflated (< (length deflated) (length data))) 8 0))
             (stored (if (= method 8) deflated data))
             (crc (crc32 data))
             (offset (fill-pointer sink)))
        (when (or (>= (length data) #xFFFFFFFF) (>= offset #xFFFFFFFF))
          (%archive-unsupported "zip entry beyond 4GiB"))
        (multiple-value-bind (time date) (%unix-to-dos-time (archive-member-mtime member))
          (%put-u32le sink #x04034b50)
          (%put-u16le sink 20)
          (%put-u16le sink flags)
          (%put-u16le sink method)
          (%put-u16le sink time)
          (%put-u16le sink date)
          (%put-u32le sink crc)
          (%put-u32le sink (length stored))
          (%put-u32le sink (length data))
          (%put-u16le sink (length name))
          (%put-u16le sink 0)
          (%put-octets sink name)
          (%put-octets sink stored)
          (push (list name flags method time date crc (length stored) (length data)
                      (logior (ash (%member-unix-mode member) 16)
                              (if (eq (archive-member-kind member) :directory) #x10 0))
                      offset)
                central))))
    (let ((directory-offset (fill-pointer sink)))
      (dolist (record (reverse central))
        (destructuring-bind (name flags method time date crc compressed size external offset) record
          (%put-u32le sink #x02014b50)
          (%put-u16le sink #x0314)
          (%put-u16le sink 20)
          (%put-u16le sink flags)
          (%put-u16le sink method)
          (%put-u16le sink time)
          (%put-u16le sink date)
          (%put-u32le sink crc)
          (%put-u32le sink compressed)
          (%put-u32le sink size)
          (%put-u16le sink (length name))
          (%put-u16le sink 0)
          (%put-u16le sink 0)
          (%put-u16le sink 0)
          (%put-u16le sink 0)
          (%put-u32le sink external)
          (%put-u32le sink offset)
          (%put-octets sink name)))
      (let ((directory-size (- (fill-pointer sink) directory-offset)))
        (when (>= (fill-pointer sink) #xFFFFFFFF) (%archive-unsupported "zip archive beyond 4GiB"))
        (%put-u32le sink #x06054b50)
        (%put-u16le sink 0)
        (%put-u16le sink 0)
        (%put-u16le sink (length members))
        (%put-u16le sink (length members))
        (%put-u32le sink directory-size)
        (%put-u32le sink directory-offset)
        (%put-u16le sink 0)))
    (coerce sink 'octets)))
