;;;; t/integration/edit-text-commands-inputs-test.lisp
;;;;
;;;; The text commands' malformed-argument refusals, stdin edits, missing
;;;; targets, and replace scan options.
(in-package #:aitools.edit.test)

(defun put-text-fixtures ()
  (put "a.txt" (format nil "a~%b~%"))
  (put "bad.bin" (octet-vector 97 #xFF 10))
  (sb-posix:mkdir (disk "empty") #o755))

(describe "aitools text commands refuse malformed arguments before writing"
  (it-each (("edit with two paths" "edit" ("a.txt" "b.txt") (:old "a" :new "b") "argument.invalid" "edit takes exactly one path")
            ("edit --stdin with --old" "edit" ("a.txt") (:stdin-data "{}" :old "a") "argument.invalid" "do not combine it")
            ("edit --stdin that is not an object" "edit" ("a.txt") (:stdin-data "[1]") "argument.invalid" "reads a JSON object")
            ("edits that are not an array" "edit" ("a.txt") (:stdin-data "{\"edits\": \"x\"}") "argument.invalid" "must be a non-empty array")
            ("empty edits" "edit" ("a.txt") (:stdin-data "{\"edits\": []}") "argument.invalid" "must be a non-empty array")
            ("an edit that is not an object" "edit" ("a.txt") (:stdin-data "{\"edits\": [1]}") "argument.invalid" "edits[0] is not an object")
            ("an edit by range" "edit" ("a.txt") (:stdin-data "{\"edits\": [{\"range\": \"1\", \"new\": \"x\"}]}") "argument.invalid" "edits[0] uses range")
            ("an edit without new" "edit" ("a.txt") (:stdin-data "{\"old\": \"a\"}") "argument.invalid" "edits[0] needs a string \"new\"")
            ("an edit with two selectors" "edit" ("a.txt") (:stdin-data "{\"old\": \"a\", \"match\": \"a\", \"new\": \"x\"}") "argument.invalid" "exactly one of old, between, match")
            ("an edit with an empty old" "edit" ("a.txt") (:stdin-data "{\"old\": \"\", \"new\": \"x\"}") "argument.invalid" "edits[0].old must be a non-empty string")
            ("an edit whose old is not a string" "edit" ("a.txt") (:stdin-data "{\"old\": 1, \"new\": \"x\"}") "argument.invalid" "edits[0].old must be a non-empty string")
            ("an edit with one between pattern" "edit" ("a.txt") (:stdin-data "{\"between\": [\"a\"], \"new\": \"x\"}") "argument.invalid" "edits[0].between must be")
            ("an edit with an empty between pattern" "edit" ("a.txt") (:stdin-data "{\"between\": [\"a\", \"\"], \"new\": \"x\"}") "argument.invalid" "edits[0].between must be")
            ("an edit whose match is not a string" "edit" ("a.txt") (:stdin-data "{\"match\": 1, \"new\": \"x\"}") "argument.invalid" "edits[0].match must be a non-empty regex")
            ("an edit by match without expect_count" "edit" ("a.txt") (:stdin-data "{\"match\": \"a\", \"new\": \"x\"}") "argument.invalid" "needs \"expect_count\"")
            ("edit --old without --new" "edit" ("a.txt") (:old "a") "argument.invalid" "--old needs --new")
            ("edit with nothing to change" "edit" ("a.txt") () "argument.invalid" "edit needs --old, a selector, or --stdin")
            ("insert with two paths" "insert" ("a.txt" "b.txt") (:at "end" :content "x") "argument.invalid" "insert takes exactly one path")
            ("insert without a position" "insert" ("a.txt") (:content "x") "argument.invalid" "insert needs exactly one of --at, --before, --after")
            ("insert --at middle" "insert" ("a.txt") (:at "middle" :content "x") "argument.invalid" "--at \"middle\" must be start or end")
            ("insert --at with a selector" "insert" ("a.txt") (:at "start" :range "1" :content "x") "argument.invalid" "--at does not take a selector")
            ("insert --before without a selector" "insert" ("a.txt") (:before t :content "x") "argument.invalid" "--before/--after need a selector")
            ("insert with --content and --stdin" "insert" ("a.txt") (:at "end" :content "x" :stdin-data "y") "argument.invalid" "pass only one of --content, --content-file, --stdin")
            ("insert from a missing --content-file" "insert" ("a.txt") (:at "end" :content-file "nope.txt") "input.not-found" "--content-file nope.txt does not exist")
            ("insert from a --content-file that is not UTF-8" "insert" ("a.txt") (:at "end" :content-file "bad.bin") "input.not-utf8" "the content-file input is not UTF-8 at byte 1")
            ("replace with only a pattern" "replace" ("a") () "argument.invalid" "replace needs PATTERN and REPLACEMENT")
            ("replace --stdin without a pattern" "replace" () (:stdin-data "{\"pattern\": 1}") "argument.invalid" "replace --stdin reads")
            ("replace --nth 0" "replace" ("a" "b" "a.txt") (:nth "0" :expect-count "1") "argument.invalid" "--nth \"0\" must be a positive integer")
            ("replace --nth x" "replace" ("a" "b" "a.txt") (:nth "x" :expect-count "1") "argument.invalid" "--nth \"x\" must be a positive integer")
            ("replace with a pattern that does not compile" "replace" ("(" "b" "a.txt") (:expect-count "1") "input.syntax-error" "bad regular expression")
            ("replace with an unknown filter" "replace" ("(a)" "${1:shout}" "a.txt") (:expect-count "1") "argument.invalid" "unknown replacement filter")
            ("replace with a selector over two files" "replace" ("a" "b" "a.txt" "bad.bin") (:range "1" :expect-count "1") "argument.invalid" "a selector needs exactly one file path")
            ("replace in a directory with no files" "replace" ("a" "b" "empty") (:expect-count "1") "selection.no-match" "no files to search")
            ("replace in a path that does not exist" "replace" ("a" "b" "nope") (:expect-count "1") "input.not-found" "nope does not exist")
            ("replace outside the workspace" "replace" ("a" "b" "/") (:expect-count "1") "refusal.outside-workspace" "is outside the workspace")
            ("replace with an unknown --lang" "replace" ("a" "b") (:lang "klingon" :expect-count "1") "input.unsupported-language" "unknown --lang \"klingon\"")
            ("replace with a malformed --skip-larger-than" "replace" ("a" "b") (:skip-larger-than "huge" :expect-count "1") "argument.invalid" "--skip-larger-than \"huge\" is not a size")
            ("replace --newer than nothing" "replace" ("a" "b") (:newer "no-such-file" :expect-count "1") "argument.invalid" "is neither a duration nor an existing path")
            ("apply with a positional" "apply" ("a.txt") (:stdin-data "x") "argument.invalid" "apply takes no positional arguments")
            ("apply without --stdin" "apply" () () "argument.invalid" "apply reads the unified diff from --stdin")
            ("apply --fuzz x" "apply" () (:stdin-data "x" :fuzz "x") "argument.invalid" "--fuzz \"x\" must be a non-negative integer")
            ("apply --strip x" "apply" () (:stdin-data "x" :strip "x") "argument.invalid" "--strip \"x\" must be a non-negative integer")
            ("apply of text without hunks" "apply" () (:stdin-data "just words") "input.syntax-error" "holds no unified diff hunks")
            ("apply of headers without hunks" "apply" () (:stdin-data "--- a/a.txt
+++ b/a.txt
") "input.syntax-error" "holds no unified diff hunks")
            ("apply of a malformed hunk header" "apply" () (:stdin-data "--- a/a.txt
+++ b/a.txt
@@ bogus @@
") "input.syntax-error" "malformed diff")
            ("transform with two paths" "transform" ("a.txt" "b.txt") (:op ("sort")) "argument.invalid" "transform takes exactly one path")
            ("transform without --op" "transform" ("a.txt") () "argument.invalid" "transform needs at least one --op")
            ("transform with an unknown op" "transform" ("a.txt") (:op ("sort" "frob")) "argument.invalid" "unknown --op \"frob\"")
            ("transform --width x" "transform" ("a.txt") (:op ("indent") :width "x") "argument.invalid" "--width \"x\" must be a non-negative integer")
            ("transform --key 0" "transform" ("a.txt") (:op ("sort") :key "0") "argument.invalid" "--key counts fields from 1")
            ("transform --columns 0" "transform" ("a.txt") (:op ("wrap") :columns "0") "argument.invalid" "--columns must be positive")
            ("transform with a delimiter that does not compile" "transform" ("a.txt") (:op ("sort") :delimiter "(") "input.syntax-error" "bad regular expression")
            ("move-lines with two paths" "move-lines" ("a.txt" "b.txt") (:range "1") "argument.invalid" "move-lines takes exactly one source path")
            ("move-lines --to-position middle" "move-lines" ("a.txt") (:range "1" :to-position "middle") "argument.invalid" "--to-position \"middle\" must be")
            ("move-lines --to-position after:0" "move-lines" ("a.txt") (:range "1" :to-position "after:0") "argument.invalid" "--to-position \"after:0\" must be")
            ("move-lines --to-position after-symbol:" "move-lines" ("a.txt") (:range "1" :to-position "after-symbol:") "argument.invalid" "must be start, end")
            ("move-lines without a selector" "move-lines" ("a.txt") (:to-position "start") "argument.invalid" "move-lines needs a selector")
            ("write with two paths" "write" ("a.txt" "b.txt") (:content ("x")) "argument.invalid" "write takes exactly one path")
            ("write with no content" "write" ("new.txt") () "argument.invalid" "no content: pass --content")
            ("write with --content and --content-file" "write" ("new.txt") (:content ("x") :content-file ("a.txt")) "argument.invalid" "not a mix")
            ("write from a missing --content-file" "write" ("new.txt") (:content-file ("a.txt" "nope.txt")) "input.not-found" "--content-file nope.txt does not exist")
            ("split with two paths" "split" ("a.txt" "b.txt") (:lines "1") "argument.invalid" "split takes exactly one path")
            ("split without a method" "split" ("a.txt") () "argument.invalid" "split needs exactly one of --lines, --at-match, --bytes")
            ("split with two methods" "split" ("a.txt") (:lines "1" :bytes "2") "argument.invalid" "split needs exactly one of")
            ("split --suffix-digits 0" "split" ("a.txt") (:lines "1" :suffix-digits "0") "argument.invalid" "--suffix-digits must be 1 to 9")
            ("split --lines 0" "split" ("a.txt") (:lines "0") "argument.invalid" "--lines must be a positive integer")
            ("split --bytes x" "split" ("a.txt") (:bytes "x") "argument.invalid" "--bytes must be a positive integer")
            ("split --at-match that does not compile" "split" ("a.txt") (:at-match "(") "input.syntax-error" "bad regular expression")
            ("transcode with two paths" "transcode" ("a.txt" "b.txt") () "argument.invalid" "transcode takes exactly one path")
            ("transcode --from klingon" "transcode" ("a.txt") (:from "klingon") "input.unsupported-format" "unsupported --from \"klingon\"")
            ("transcode --to klingon" "transcode" ("a.txt") (:to "klingon") "input.unsupported-format" "unsupported --to \"klingon\""))
      "refuses ~A"
      (name command positionals options code fragment)
    (declare (ignore name))
    (with-workspace ()
      (put-text-fixtures)
      (let ((before (snapshot)))
        (with-error (actual message) (apply #'run command positionals options)
          (expect actual :to-equal code)
          (expect (search fragment message) :to-be-truthy))
        (expect-unchanged before)))))

(describe "aitools edit and insert: stdin edits, missing targets and selections"
  (it "applies edits[] chosen by between and by match with its own expect_count"
    (with-workspace ()
      (put "a.txt" (format nil "begin~%x~%end~%y1~%y2~%z~%"))
      (setf *stdin* (bytes (concatenate 'string
                                        "{\"edits\": [{\"between\": [\"^begin$\", \"^end$\"], \"exclusive\": true, \"new\": \"X\"},"
                                        " {\"match\": \"^z$\", \"invert\": true, \"expect_count\": 4, \"new\": \"-\"}]}")))
      (with-error (code) (run "edit" '("a.txt") :stdin t) (expect code :to-equal "selection.count-mismatch"))
      (setf *stdin* (bytes (concatenate 'string
                                        "{\"edits\": [{\"between\": [\"^begin$\", \"^end$\"], \"exclusive\": true, \"new\": \"X\"},"
                                        " {\"match\": \"^y\", \"expect_count\": 2, \"new\": \"Y\"}]}")))
      (multiple-value-bind (kind fields) (run "edit" '("a.txt") :stdin t)
        (expect kind :to-be :ok)
        (expect (assoc "strategy" fields :test #'string=) :to-be nil))
      (expect (text "a.txt") :to-equal (format nil "begin~%X~%end~%Y~%Y~%z~%"))))

  (it "names similar files for a missing target and refuses a directory"
    (with-workspace ()
      (put "notes.txt" "n")
      (put "src/main.lisp" "m")
      (sb-posix:mkdir (disk "dir") #o755)
      (with-error (code message keys) (run "edit" '("note.txt") :old "a" :new "b")
        (expect code :to-equal "input.not-found")
        (expect (mapcar (lambda (candidate) (json-field candidate "path")) (getf keys :candidates))
                :to-equal '("notes.txt" "dir" "src")))
      (with-error (code message keys) (run "edit" '("src/mian.lisp") :old "a" :new "b")
        (expect code :to-equal "input.not-found")
        (expect (json-field (first (getf keys :candidates)) "path") :to-equal "src/main.lisp"))
      (with-error (code message) (run "edit" '("dir") :old "a" :new "b")
        (expect code :to-equal "refusal.not-a-file")
        (expect message :to-equal "dir is a directory, not a file"))))

  (it "refuses a --symbol that names two definitions, and one that names none"
    (with-workspace ()
      (put "c.lisp" (format nil "(defun a () 1)~%(defun a () 2)~%"))
      (with-error (code message keys) (run "edit" '("c.lisp") :symbol "a" :new "x" :expect-hash (list (hash "c.lisp")))
        (expect code :to-equal "selection.ambiguous")
        (expect (length (getf keys :candidates)) :to-be 2))
      (with-error (code) (run "edit" '("c.lisp") :symbol "zz" :new "x" :expect-hash (list (hash "c.lisp")))
        (expect code :to-equal "selection.no-match"))))

  (it "inserts a --content-file's text"
    (with-workspace ()
      (put "a.txt" (format nil "a~%"))
      (put "in.txt" (format nil "b~%"))
      (expect (run "insert" '("a.txt") :at "end" :content-file "in.txt") :to-be :ok)
      (expect (text "a.txt") :to-equal (format nil "a~%b~%")))))

(describe "aitools replace: stdin, scan options and unreadable files"
  (it "reads the pattern and replacement from --stdin"
    (with-workspace ()
      (put "a.txt" (format nil "cat~%"))
      (setf *stdin* (bytes "{\"pattern\": \"c(a)t\", \"replacement\": \"d${1}g\"}"))
      (expect (run "replace" '("a.txt") :stdin t :expect-count "1") :to-be :ok)
      (expect (text "a.txt") :to-equal (format nil "dag~%"))))

  (it "points a refusal's repair at the searched path, never at the pattern"
    (with-workspace ()
      (sb-posix:mkdir (disk "src") #o755)
      (put "src/a.txt" (format nil "v~%"))
      (with-error (code message keys) (run "replace" '("v" "w" "src") :lang "klingon" :expect-count "1")
        (expect code :to-equal "input.unsupported-language")
        (expect (repair-commands keys) :to-equal '("aitools read src")))
      (with-error (code message keys) (run "replace" '("v" "w") :lang "klingon" :expect-count "1")
        (expect code :to-equal "input.unsupported-language")
        (expect (repair-commands keys) :to-equal '("aitools schema replace")))
      (setf *stdin* (bytes "{\"pattern\": \"v\", \"replacement\": \"w\"}"))
      (with-error (code message keys) (run "replace" '("src") :stdin t :lang "klingon" :expect-count "1")
        (expect code :to-equal "input.unsupported-language")
        (expect (repair-commands keys) :to-equal '("aitools read src")))))

  (it "refuses a named binary file but skips binary and non-UTF-8 files found by the scan"
    (with-workspace ()
      (put "a.txt" (format nil "foo~%"))
      (put "b.bin" (octet-vector 102 111 111 0))
      (put "c.txt" (octet-vector 102 111 111 #xFF))
      (with-error (code) (run "replace" '("foo" "bar" "b.bin") :expect-count "1")
        (expect code :to-equal "refusal.not-a-file"))
      (expect (run "replace" '("foo" "bar") :expect-count "1") :to-be :ok)
      (expect (text "a.txt") :to-equal (format nil "bar~%"))
      (expect (octets-of "b.bin") :to-equalp (octet-vector 102 111 111 0))))

  (it "skips a scanned file whose selector does not match instead of refusing"
    (with-workspace ()
      (put "a.txt" (format nil "k v~%"))
      (with-error (code) (run "replace" '("v" "w" "a.txt") :between '("^nope" "^never") :expect-count "1")
        (expect code :to-equal "selection.no-match"))))

  (it "limits the scan with --newer by duration and by a reference file, and with --lang"
    (with-workspace ()
      (put "old.txt" (format nil "v~%"))
      (put "new.lisp" (format nil "v~%"))
      (sb-posix:utimes (disk "old.txt") 0 0)
      (put "ref" "r")
      (sb-posix:utimes (disk "ref") 1000 1000)
      (expect (run "replace" '("v" "w") :newer "1h" :expect-count "1") :to-be :ok)
      (expect (text "new.lisp") :to-equal (format nil "w~%"))
      (expect (run "replace" '("w" "x") :newer "ref" :expect-count "1") :to-be :ok)
      (expect (text "new.lisp") :to-equal (format nil "x~%"))
      (expect (run "replace" '("v" "y") :lang "common-lisp" :expect-count "0") :to-be :ok)
      (expect (text "old.txt") :to-equal (format nil "v~%")))))

  (it "uses the injected edit clock for --newer durations"
    (with-workspace ()
      (put "old.txt" "v")
      (put "new.txt" "v")
      (sb-posix:utimes (disk "old.txt") 1000 1000)
      (sb-posix:utimes (disk "new.txt") 99000 99000)
      (let ((ports *ports*))
        (setf *ports*
              (make-edit-ports
               :workspace-host (aitools.edit.application::edit-ports-workspace-host ports)
               :open-store (aitools.edit.application::edit-ports-open-store ports)
               :text-source (aitools.edit.application::edit-ports-text-source ports)
               :read-stdin-octets (aitools.edit.application::edit-ports-read-stdin-octets ports)
               :unix-now (lambda () 100000)))
        (expect (run "replace" '("v" "w") :newer "1h" :expect-count "1") :to-be :ok)
        (expect (text "old.txt") :to-equal "v")
        (expect (text "new.txt") :to-equal "w"))))

  (it "treats an existing duration-shaped --newer path as a path"
    (with-workspace ()
      (put "7d" "v")
      (put "new.txt" "v")
      (sb-posix:utimes (disk "7d") 1000 1000)
      (sb-posix:utimes (disk "new.txt") 1500 1500)
      (expect (run "replace" '("v" "w") :newer "7d" :expect-count "1") :to-be :ok)
      (expect (text "7d") :to-equal "v")
      (expect (text "new.txt") :to-equal "w")))

  (it "reports an oversized file skipped by a path-based --newer scan"
    (with-workspace ()
      (put "7d" "ref")
      (put "small.txt" "v")
      (put "big.txt" (make-string 2048 :initial-element #\v))
      (sb-posix:utimes (disk "7d") 1000 1000)
      (sb-posix:utimes (disk "small.txt") 1500 1500)
      (sb-posix:utimes (disk "big.txt") 1500 1500)
      (multiple-value-bind (kind fields)
          (run "replace" '("v" "w") :newer "7d" :skip-larger-than "1KiB" :expect-count "1")
        (expect kind :to-be :ok)
        (expect (changes fields) :to-equal '(("small.txt" "modified")))
        (expect (mapcar (lambda (entry) (json-field entry "path")) (field fields "skipped"))
                :to-equal '("big.txt"))
        (expect (json-field (first (field fields "skipped")) "reason") :to-equal "too-large")
        (expect (text "small.txt") :to-equal "w")
        (expect (text "big.txt") :to-equal (make-string 2048 :initial-element #\v)))))
