;;;; t/integration/store-write-protocol-test.lisp
;;;;
;;;; The write protocol and the journal against a real temporary workspace and state
;;;; directory through the production adapter.
(in-package #:aitools.store.test)

(describe "aitools.store commit-changes/k"
  (it "applies every action and reports before/after states and bytes"
    (with-temp-store (store)
      (put-file store "edit.txt" "old")
      (put-file store "gone.txt" "bye")
      (put-file store "mv.txt" "moving")
      (put-file store "exec.sh" "#!/bin/sh")
      (multiple-value-bind (status op-id results)
          (commit store (list (write-file-request "new/deep.txt" (bytes "fresh"))
                              (write-file-request "edit.txt" (bytes "new"))
                              (delete-request "gone.txt")
                              (move-request "mv.txt" "moved.txt")
                              (chmod-request "exec.sh" #o755)
                              (symlink-request "link" "edit.txt")))
        (expect status :to-be :committed)
        (expect (valid-op-id-p op-id) :to-be-truthy)
        (expect (actions results)
                :to-equal '(("new" :created) ("new/deep.txt" :created) ("edit.txt" :modified)
                            ("gone.txt" :deleted) ("moved.txt" :moved) ("exec.sh" :mode-changed)
                            ("link" :linked)))
        (let ((edit (find "edit.txt" results :key #'change-result-path :test #'string=)))
          (expect (octets-string (change-result-before-content edit)) :to-equal "old")
          (expect (octets-string (change-result-after-content edit)) :to-equal "new")
          (expect (change-result-hash-after edit)
                  :to-equal (aitools.kernel.domain:content-hash (bytes "new"))))
        (expect (change-result-from (find "moved.txt" results :key #'change-result-path :test #'string=))
                :to-equal "mv.txt"))
      (expect (disk-text store "new/deep.txt") :to-equal "fresh")
      (expect (disk-text store "edit.txt") :to-equal "new")
      (expect (disk-text store "gone.txt") :to-be :absent)
      (expect (disk-text store "mv.txt") :to-be :absent)
      (expect (disk-text store "moved.txt") :to-equal "moving")
      (expect (disk-mode store "exec.sh") :to-be #o755)
      (expect (entry-state-target (workspace-state store "link")) :to-equal "edit.txt")
      (expect (temp-files store) :to-equal '())
      (expect (intent-files store) :to-equal '())
      (expect (length (read-journal store)) :to-be 1)))

  (it "writes nothing and returns no op id for --dry-run"
    (with-temp-store (store)
      (put-file store "a.txt" "a")
      (multiple-value-bind (status op-id results) (commit store (list (write-file-request "a.txt" (bytes "b"))) :dry-run t)
        (expect status :to-be :committed)
        (expect op-id :to-be nil)
        (expect (actions results) :to-equal '(("a.txt" :modified))))
      (expect (disk-text store "a.txt") :to-equal "a")
      (expect (read-journal store) :to-equal '())))

  (it "returns no op and no journal entry when nothing changes"
    (with-temp-store (store)
      (put-file store "d/x" "x")
      (multiple-value-bind (status op-id results) (commit store (list (mkdir-request "d")))
        (expect status :to-be :committed)
        (expect op-id :to-be nil)
        (expect results :to-equal '()))
      (expect (read-journal store) :to-equal '())))

  (it "passes a validation rejection through untouched and writes nothing"
    (with-temp-store (store)
      (put-file store "a.txt" "a")
      (multiple-value-bind (status code message keys)
          (commit-changes/k store '("edit")
                            (lambda (commit reject)
                              (declare (ignore commit))
                              (funcall reject "selection.no-match" "no match" :candidates '("a.txt")))
                            :on-committed (lambda (&rest args) (declare (ignore args)) :committed)
                            :on-rejected (lambda (code message &rest keys) (values :rejected code message keys))
                            :on-busy (lambda () :busy))
        (expect status :to-be :rejected)
        (expect code :to-equal "selection.no-match")
        (expect message :to-equal "no match")
        (expect (getf keys :candidates) :to-equal '("a.txt")))
      (expect (disk-text store "a.txt") :to-equal "a")))

  (it "rejects an I/O failure before the commit point as environment.io and leaves nothing"
    (with-temp-store (store)
      (put-file store "a.txt" "a")
      (let* ((io (store-io-port store))
             (failing (copy-store-io io :append-file (lambda (&rest args)
                                                       (declare (ignore args))
                                                       (error 'store-io-error :operation "write" :path "x"))))
             (broken (make-store failing (store-root store)
                                 (subseq (store-state-directory store) 0
                                         (position #\/ (store-state-directory store) :from-end t)))))
        (expect (nth-value 1 (commit broken (list (write-file-request "a.txt" (bytes "b"))))) :to-equal "environment.io"))
      (expect (disk-text store "a.txt") :to-equal "a")
      (expect (temp-files store) :to-equal '())
      (expect (intent-files store) :to-equal '())))

  (it "validates after the lock is held (TOCTOU)"
    ;; A fake adapter that rewrites the target at the moment the lock is
    ;; granted, i.e. just before validation would run. Validation must see
    ;; the rewritten content; a validate-then-lock implementation sees "v1".
    (with-temp-store (plain)
      (put-file plain "a.txt" "v1")
      (let* ((io (store-io-port plain))
             (real-try-lock (store-io-try-lock io))
             (mutating (copy-store-io io :try-lock (lambda (path &rest keys)
                                                     (let ((handle (apply real-try-lock path keys)))
                                                       (when handle (put-file plain "a.txt" "v2"))
                                                       handle))))
             (store (make-store mutating (store-root plain)
                                (subseq (store-state-directory plain) 0
                                        (position #\/ (store-state-directory plain) :from-end t))))
             (seen nil))
        (commit-changes/k store '("edit")
                          (lambda (commit reject)
                            (declare (ignore reject))
                            (setf seen (disk-text plain "a.txt"))
                            (funcall commit (list (write-file-request "a.txt" (bytes "v3")))))
                          :on-committed (lambda (&rest args) (declare (ignore args)))
                          :on-rejected (lambda (&rest args) (declare (ignore args)))
                          :on-busy (lambda ()))
        (expect seen :to-equal "v2")
        (expect (disk-text plain "a.txt") :to-equal "v3"))))

  (it "replaces a symlink itself rather than writing through it"
    (with-temp-store (store)
      (put-file store "real.txt" "r")
      (commit store (list (symlink-request "l" "real.txt")))
      (commit store (list (write-file-request "l" (bytes "replaced"))))
      (expect (entry-state-kind (workspace-state store "l")) :to-be :file)
      (expect (disk-text store "real.txt") :to-equal "r"))))

(describe "aitools.store journal and undo"
  (it "records argv, time, and every change's before/after"
    (with-temp-store (store)
      (put-file store "a.txt" "a")
      (let ((op-id (nth-value 1 (commit store (list (write-file-request "a.txt" (bytes "b"))) :argv '("write" "a.txt")))))
        (let ((entry (find-journal-entry store op-id)))
          (expect (journal-entry-argv entry) :to-equal '("write" "a.txt"))
          (expect (length (journal-entry-time entry)) :to-be 20)
          (expect (entry-state-hash (change-result-before (first (journal-entry-changes entry))))
                  :to-equal (aitools.kernel.domain:content-hash (bytes "a")))
          (expect (octets-string (read-blob store (entry-state-hash (change-result-before (first (journal-entry-changes entry))))))
                  :to-equal "a")))))

  (it "restores bytes, mode, and existence for every action, as a new op with undoes"
    (with-temp-store (store)
      (put-file store "edit.txt" "old")
      (put-file store "gone.txt" "bye" :mode #o600)
      (put-file store "mv.txt" "moving")
      (put-file store "exec.sh" "#!/bin/sh")
      (put-file store "over.txt" "overwritten")
      (let ((op-id (nth-value 1 (commit store (list (write-file-request "new/deep.txt" (bytes "fresh"))
                                                    (write-file-request "edit.txt" (bytes "new"))
                                                    (delete-request "gone.txt")
                                                    (move-request "mv.txt" "moved.txt")
                                                    (move-request "over.txt" "edit2.txt")
                                                    (chmod-request "exec.sh" #o755)
                                                    (symlink-request "link" "edit.txt"))))))
        (multiple-value-bind (status undo-op) (undo store op-id)
          (expect status :to-be :committed)
          (expect (journal-entry-undoes (find-journal-entry store undo-op)) :to-equal op-id))
        (expect (disk-text store "new") :to-be :absent)
        (expect (disk-text store "edit.txt") :to-equal "old")
        (expect (disk-text store "gone.txt") :to-equal "bye")
        (expect (disk-mode store "gone.txt") :to-be #o600)
        (expect (disk-text store "mv.txt") :to-equal "moving")
        (expect (disk-text store "moved.txt") :to-be :absent)
        (expect (disk-text store "over.txt") :to-equal "overwritten")
        (expect (disk-mode store "exec.sh") :to-be #o644)
        (expect (disk-text store "link") :to-be :absent))))

  (it "refuses with refusal.target-changed and conflicts when a path changed later"
    (with-temp-store (store)
      (put-file store "a.txt" "a")
      (put-file store "b.txt" "b")
      (let ((op-id (nth-value 1 (commit store (list (write-file-request "a.txt" (bytes "a2"))
                                                    (write-file-request "b.txt" (bytes "b2")))))))
        (put-file store "b.txt" "someone else")
        (multiple-value-bind (status code message keys) (undo store op-id)
          (declare (ignore message))
          (expect status :to-be :rejected)
          (expect code :to-equal "refusal.target-changed")
          (expect (mapcar #'conflict-path (getf keys :conflicts)) :to-equal '("b.txt")))
        (expect (disk-text store "a.txt") :to-equal "a2")
        (expect (disk-text store "b.txt") :to-equal "someone else"))))

  (it "refuses to remove a created directory that has gained a file"
    (with-temp-store (store)
      (let ((op-id (nth-value 1 (commit store (list (write-file-request "d/f.txt" (bytes "x")))))))
        (put-file store "d/other.txt" "mine")
        (multiple-value-bind (status code message keys) (undo store op-id)
          (declare (ignore message))
          (expect status :to-be :rejected)
          (expect code :to-equal "refusal.target-changed")
          (expect (mapcar #'conflict-path (getf keys :conflicts)) :to-equal '("d/other.txt")))
        (expect (disk-text store "d/f.txt") :to-equal "x"))))

  (it "redoes through undo of the undo, including an overwriting move"
    (with-temp-store (store)
      (put-file store "src.txt" "S")
      (put-file store "dst.txt" "D")
      (put-file store "a.txt" "1")
      (let* ((op (nth-value 1 (commit store (list (move-request "src.txt" "dst.txt")
                                                  (write-file-request "a.txt" (bytes "2"))))))
             (undo-op (nth-value 1 (undo store op))))
        (expect (list (disk-text store "src.txt") (disk-text store "dst.txt") (disk-text store "a.txt"))
                :to-equal '("S" "D" "1"))
        (expect (undo store undo-op) :to-be :committed)
        (expect (list (disk-text store "src.txt") (disk-text store "dst.txt") (disk-text store "a.txt"))
                :to-equal '(:absent "S" "2")))))

  (it "answers input.not-found for an unknown or malformed op id"
    (with-temp-store (store)
      (expect (nth-value 1 (undo store (format-op-id 3964000000 "00000000"))) :to-equal "input.not-found")
      (expect (nth-value 1 (undo store "../../etc/passwd")) :to-equal "input.not-found")))

  (it "deletes the oldest generation on the 21st write and collects its blob"
    (with-temp-store (store)
      (put-file store "a.txt" "v0")
      (let ((first-op (nth-value 1 (commit store (list (write-file-request "a.txt" (bytes "v1")))))))
        (loop for n from 2 to 20
              do (commit store (list (write-file-request "a.txt" (bytes (format nil "v~D" n))))))
        (expect (length (read-journal store)) :to-be 20)
        (expect (find-journal-entry store first-op) :to-be-truthy)
        (let ((v0-hash (aitools.kernel.domain:content-hash (bytes "v0")))
              (blobs (blobs-directory (store-state-directory store))))
          (expect (member v0-hash (funcall (store-io-list-directory (store-io-port store)) blobs) :test #'string=)
                  :to-be-truthy)
          (commit store (list (write-file-request "a.txt" (bytes "v21"))))
          (expect (length (read-journal store)) :to-be 20)
          (expect (find-journal-entry store first-op) :to-be nil)
          (expect (member v0-hash (funcall (store-io-list-directory (store-io-port store)) blobs) :test #'string=)
                  :to-be-falsy)
          (expect (member (aitools.kernel.domain:content-hash (bytes "v1"))
                          (funcall (store-io-list-directory (store-io-port store)) blobs) :test #'string=)
                  :to-be-truthy))))))
