#!/usr/bin/env perl
# Regenerates data/domain/text/{cp932,euc-jp}-data.lisp from glibc's
# localedata charmaps (share/i18n/charmaps/WINDOWS-31J.gz and EUC-JP.gz in
# the glibc output of nixpkgs; any glibc 2.42 build ships byte-identical
# tables). Usage, from the repository root:
#
#   gzip -dc <glibc>/share/i18n/charmaps/WINDOWS-31J.gz \
#     | perl data/domain/text/generate-charmap-data.pl cp932 'glibc 2.42 WINDOWS-31J' \
#     > data/domain/text/cp932-data.lisp
#   gzip -dc <glibc>/share/i18n/charmaps/EUC-JP.gz \
#     | perl data/domain/text/generate-charmap-data.pl euc-jp 'glibc 2.42 EUC-JP' \
#     > data/domain/text/euc-jp-data.lisp
#
# Each CHARMAP line "<Uxxxx> /xHH[/xHH...] NAME" becomes one triple
# (byte-code code-point reversible), byte-code being the byte sequence read
# as a big-endian integer. Lines glibc prefixes with %IRREVERSIBLE% decode
# but are never chosen when encoding (reversible 0).
use strict;
use warnings;

my ($name, $source) = @ARGV;
die "usage: generate-charmap-data.pl NAME SOURCE-LABEL < charmap\n" unless defined $source;

my @triples;
my $in_map = 0;
while (my $line = <STDIN>) {
  if ($line =~ /^CHARMAP/) { $in_map = 1; next; }
  if ($line =~ /^END CHARMAP/) { last; }
  next unless $in_map;
  next unless $line =~ m{^(%IRREVERSIBLE%)?<U([0-9A-Fa-f]+)>\s+((?:/x[0-9a-fA-F]{2})+)\s};
  my ($irreversible, $unicode, $bytes) = ($1, hex($2), $3);
  my $code = 0;
  $code = $code * 256 + hex($1) while $bytes =~ m{/x([0-9a-fA-F]{2})}g;
  push @triples, [$code, $unicode, $irreversible ? 0 : 1];
}
die "no CHARMAP entries read\n" unless @triples;
@triples = sort { $a->[0] <=> $b->[0] || $b->[2] <=> $a->[2] } @triples;

my $symbol = "*${name}-mapping*";
print ";;;; data/domain/text/${name}-data.lisp\n";
print ";;;;\n";
print ";;;; GENERATED by data/domain/text/generate-charmap-data.pl from $source\n";
print ";;;; (glibc localedata charmap). Do not edit by hand; regenerate instead.\n";
print ";;;; A flat vector of (byte-code code-point reversible) triples sorted by\n";
print ";;;; byte-code; REVERSIBLE 0 marks a decode-only mapping.\n";
print "(in-package #:aitools.data)\n\n";
print "(defparameter $symbol\n  #(";
my $first = 1;
my $count = 0;
for my $t (@triples) {
  if ($count > 0 && $count % 6 == 0) { print "\n    "; }
  elsif (!$first) { print " "; }
  print join(" ", @$t);
  $first = 0;
  $count++;
}
print "))\n\n(export '$symbol)\n";
