;;;; t/unit/workspace/wildmatch-test.lisp
;;;;
;;;; Cases from git's t/t3070-wildmatch.sh. Each row is (pattern text
;;;; with-pathname without-pathname); the gitignore parity integration test
;;;; checks the same matcher against a real git.
(in-package #:aitools.workspace.test)

(defparameter *wildmatch-cases*
  '(("foo" "foo" t t)
    ("bar" "foo" nil nil)
    ("" "" t t)
    ("???" "foo" t t)
    ("??" "foo" nil nil)
    ("*" "foo" t t)
    ("f*" "foo" t t)
    ("*f" "foo" nil nil)
    ("*foo*" "foo" t t)
    ("*ob*a*r*" "foobar" t t)
    ("*ab" "aaaaaaabababab" t t)
    ("foo\\*" "foo*" t t)
    ("foo\\*bar" "foobar" nil nil)
    ("f\\\\oo" "f\\oo" t t)
    ("*[al]?" "ball" t t)
    ("[ten]" "ten" nil nil)
    ("**[!te]" "ten" t t)
    ("**[!ten]" "ten" nil nil)
    ("t[a-g]n" "ten" t t)
    ("t[!a-g]n" "ten" nil nil)
    ("t[!a-g]n" "ton" t t)
    ("t[^a-g]n" "ton" t t)
    ("a[]]b" "a]b" t t)
    ("a[]-]b" "a-b" t t)
    ("a[]-]b" "a]b" t t)
    ("a[]-]b" "aab" nil nil)
    ("a[]a-]b" "aab" t t)
    ("]" "]" t t)
    ("foo*bar" "foo/baz/bar" nil t)
    ("foo**bar" "foo/baz/bar" nil t)
    ("foo**bar" "foobazbar" t t)
    ("foo/**/bar" "foo/baz/bar" t t)
    ("foo/**/**/bar" "foo/baz/bar" t nil)
    ("foo/**/bar" "foo/b/a/z/bar" t t)
    ("foo/**/**/bar" "foo/b/a/z/bar" t t)
    ("foo/**/bar" "foo/bar" t nil)
    ("foo/**/**/bar" "foo/bar" t nil)
    ("foo?bar" "foo/bar" nil t)
    ("foo[/]bar" "foo/bar" nil t)
    ("foo[^a-z]bar" "foo/bar" nil t)
    ("f[^eiu][^eiu][^eiu][^eiu][^eiu]r" "foo/bar" nil t)
    ("f[^eiu][^eiu][^eiu][^eiu][^eiu]r" "foo-bar" t t)
    ("**/foo" "foo" t nil)
    ("**/foo" "XXX/foo" t t)
    ("**/foo" "bar/baz/foo" t t)
    ("*/foo" "bar/baz/foo" nil t)
    ("**/bar*" "foo/bar/baz" nil t)
    ("**/bar/*" "deep/foo/bar/baz" t t)
    ("**/bar/*" "deep/foo/bar/baz/" nil t)
    ("**/bar/**" "deep/foo/bar/baz/" t t)
    ("**/bar/*" "deep/foo/bar" nil nil)
    ("**/bar/**" "deep/foo/bar/" t t)
    ("**/bar**" "foo/bar/baz" nil t)
    ("*/bar/**" "foo/bar/baz/x" t t)
    ("*/bar/**" "deep/foo/bar/baz/x" nil t)
    ("**/bar/*/*" "deep/foo/bar/baz/x" t t)
    ("[[:alpha:]][[:digit:]][[:upper:]]" "a1B" t t)
    ("[[:digit:][:upper:][:space:]]" "a" nil nil)
    ("[[:digit:][:upper:][:space:]]" "A" t t)
    ("[[:digit:][:upper:][:space:]]" "1" t t)
    ("[[:digit:][:upper:][:space:]]" " " t t)
    ("[[:xdigit:]]" "5" t t)
    ("[[:xdigit:]]" "f" t t)
    ("[[:xdigit:]]" "g" nil nil)
    ("[a-c[:digit:]x-z]" "5" t t)
    ("[a-c[:digit:]x-z]" "b" t t)
    ("[a-c[:digit:]x-z]" "y" t t)
    ("[a-c[:digit:]x-z]" "q" nil nil)
    ("*/*/*" "foo/bba/arr" t t)
    ("*/*/*" "foo/bb/aa/rr" nil t)
    ("**/**/**" "foo/bb/aa/rr" t t)
    ("*X*i" "abcXdefXghi" t t)
    ("*/*X*/*/*i" "ab/cXd/efXg/hi" t t)
    ("**/*X*/**/*i" "ab/cXd/efXg/hi" t t)
    ("-*-*-*-*-*-*-12-*-*-*-m-*-*-*" "-adobe-courier-bold-o-normal--12-120-75-75-m-70-iso8859-1" t t)
    ("[[:bogus:]]" "a" nil nil)))

(describe "aitools.workspace.domain wildmatch"
  (it "matches git's t3070 cases with and without WM_PATHNAME"
    (let ((failures
            (loop for (pattern text pathname plain) in *wildmatch-cases*
                  unless (and (eq pathname (wildmatch pattern text :pathname t))
                              (eq plain (wildmatch pattern text)))
                    collect (list pattern text))))
      (expect failures :to-equal nil)))

  (it "folds ASCII case only when asked"
    (expect (wildmatch "FOO" "foo" :pathname t) :to-be-falsy)
    (expect (wildmatch "FOO" "foo" :pathname t :casefold t) :to-be-truthy)
    (expect (wildmatch "[A-Z]" "a" :casefold t) :to-be-truthy)
    (expect (wildmatch "[[:upper:]]" "a" :casefold t) :to-be-truthy)))
